name = "ParameterizedQuantumControl"
uuid = "409be4c9-afa4-4246-894e-472b92a1ed06"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
QuantumGradientGenerators = "a563f35e-61db-434d-8c01-8b9e3ccdfd85"

[compat]
LinearAlgebra = "1"
QuantumControlBase = ">=0.9.0"
QuantumGradientGenerators = ">=0.1.4"
julia = "1.9"
