name = "ParameterizedQuantumControl"
uuid = "409be4c9-afa4-4246-894e-472b92a1ed06"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.2+dev"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumGradientGenerators = "a563f35e-61db-434d-8c01-8b9e3ccdfd85"

[weakdeps]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"

[extensions]
ParameterizedQuantumControlOptimizationExt = "Optimization"

[compat]
LinearAlgebra = "1"
Optimization = "3"
QuantumControl = ">=0.11.0"
QuantumGradientGenerators = ">=0.1.8"
julia = "1.9"
